// The .source folder is generated by fumadocs-mdx (postinstall / next build).
// Only the /docs route reads through here. Guides use their own filesystem
// scanner in src/config/guides-content.ts (gray-matter + fs, build-time only).
import { createElement } from 'react';
import { docs } from '@/.source';
import type { I18nConfig } from 'fumadocs-core/i18n';
import { loader } from 'fumadocs-core/source';
import { icons } from 'lucide-react';

import { defaultLocale, locales } from '@/config/locale';

/**
 * Derived from the site's published locales, never hardcoded. A fixed list here
 * would disagree with the language switcher in the (docs) layout, which reads
 * `locales` — offering languages that have no pages, or omitting ones that do.
 *
 * `parser: 'dot'` matches the content convention used across the template:
 * `page.mdx` is the default locale, `page.zh.mdx` is a translation.
 */
export const i18n: I18nConfig = {
  defaultLanguage: defaultLocale,
  languages: [...locales],
  parser: 'dot',
  hideLocale: 'default-locale',
};

/** Resolve a frontmatter `icon: Swords` string to a lucide element. */
const resolveIcon = (icon: string | undefined) => {
  if (!icon) return;
  if (icon in icons) return createElement(icons[icon as keyof typeof icons]);
};

export const docsSource = loader({
  baseUrl: '/docs',
  source: docs.toFumadocsSource(),
  i18n,
  icon: resolveIcon,
});

export const source = docsSource;
